

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const TODO_TOGGLE_PINTOTOP = 'TODO_TOGGLE_PINTOTOP';
export const TODO_TOGGLE_IMPORTANT = 'TODO_TOGGLE_IMPORTANT';
export const TODO_TOGGLE_DONE = 'TODO_TOGGLE_DONE';
